version: '3.3'
services:
  trellito:
    env_file: .env.local
    image: 'trellito'
    restart: 'always'
    build:
      context: ./
    volumes:
      - ./trellito:/usr/src
      - /usr/src/node_modules
    ports:
      - 3000:3000
    container_name: 'trellito'
    working_dir: '/usr/src'
    stdin_open: true
    tty: true
    networks:
      - local

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/var/lib/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: K2p4m.g3L90
    domainname: mongo.dev.localhost
    networks:
      - local

volumes:
  mongo_data: {}

networks:
  local:
    driver: bridge
