import Head from 'next/head'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

interface IRoute {
  route: string
  label: string
}

interface IPage {
  title: string
  children: React.ReactNode
  auth?: boolean
}

export const Page: React.FC<IPage> = ({ children, title }) => {
  const routes: IRoute[] = [
    {
      route: '/boards',
      label: 'Boards'
    }
  ]

  return (
    <>
      <Head>
        <title>Trellito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header routes={routes} />
        {children}
        <Footer />
      </main>
    </>
  )
}
