import Head from 'next/head'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { ReadonlyURLSearchParams, useSearchParams } from 'next/navigation'
import { Toast } from '@/components/Toast'

interface Route {
  route: string
  label: string
}

interface PageProps {
  title: string
  children: React.ReactNode
  auth?: boolean
}

const Page: React.FC<PageProps> = ({ children, title }) => {
  const searchParams: ReadonlyURLSearchParams = useSearchParams()
  const error: string | null = searchParams.get('error')

  const routes: Route[] = [
    {
      route: '/boards',
      label: 'Boards'
    }
  ]

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header routes={routes} />
        {children}
        <Footer />
        {error && <Toast duration={10000} severity="error" message={error} />}
      </main>
    </>
  )
}

export default Page
